environment:
  # https://github.com/jasongin/nvs/blob/master/doc/CI.md
  NVS_VERSION: 1.2.0
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "1.8"
    - nodejs_version: "2.5"
    - nodejs_version: "3.3"
    - nodejs_version: "4.8"
    - nodejs_version: "5.12"
    - nodejs_version: "6.10"
    - nodejs_version: "7.6"
    - nodejs_version: chakracore  
cache:
  - node_modules
install:
  - ps: >-
      if ($env:nodejs_version -eq "chakracore") {
        # nvs
        git clone --branch v%NVS_VERSION% --depth 1 https://github.com/jasongin/nvs %LOCALAPPDATA%\nvs
        set PATH=%LOCALAPPDATA%\nvs;%PATH%
        nvs --version
        # node-chakracore
        nvs add chakracore
        nvs use chakracore
      } else {
        # node-v8
        Install-Product node $env:nodejs_version $env:platform
      }
  - npm rm --save-dev connect-redis
  - if exist node_modules npm prune
  - if exist node_modules npm rebuild
  - npm install
build: off
test_script:
  - node --version
  - npm --version
  - npm run test-ci
version: "{build}"
